/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum OpalMessageType {
  OpalIndCommandError,
  OpalCmdSetGeneralParameters,
  OpalCmdSetProtocolParameters,
  OpalCmdRegistration,
  OpalIndRegistration,
  OpalCmdSetUpCall,
  OpalIndIncomingCall,
  OpalCmdAnswerCall,
  OpalCmdClearCall,
  OpalIndAlerting,
  OpalIndEstablished,
  OpalIndUserInput,
  OpalIndCallCleared,
  OpalCmdHoldCall,
  OpalCmdRetrieveCall,
  OpalCmdTransferCall,
  OpalCmdUserInput,
  OpalIndMessageWaiting,
  OpalIndMediaStream,
  OpalCmdMediaStream,
  OpalCmdSetUserData,
  OpalIndLineAppearance,
  OpalCmdStartRecording,
  OpalCmdStopRecording,
  OpalIndProceeding,
  OpalCmdAlerting,
  OpalIndOnHold,
  OpalIndOffHold,
  OpalIndTransferCall,
  OpalIndCompletedIVR,
  OpalCmdAuthorisePresence,
  OpalCmdSubscribePresence,
  OpalCmdSetLocalPresence,
  OpalIndPresenceChange,
  OpalCmdSendIM,
  OpalIndReceiveIM,
  OpalIndSentIM,
  OpalMessageTypeCount
}
