//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OpalStatusTransferCall : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalStatusTransferCall(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpalStatusTransferCall obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalStatusTransferCall() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalStatusTransferCall(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string callToken {
    set {
      OPALPINVOKE.OpalStatusTransferCall_callToken_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusTransferCall_callToken_get(swigCPtr);
      return ret;
    } 
  }

  public string protocolCallId {
    set {
      OPALPINVOKE.OpalStatusTransferCall_protocolCallId_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusTransferCall_protocolCallId_get(swigCPtr);
      return ret;
    } 
  }

  public string result {
    set {
      OPALPINVOKE.OpalStatusTransferCall_result_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusTransferCall_result_get(swigCPtr);
      return ret;
    } 
  }

  public string info {
    set {
      OPALPINVOKE.OpalStatusTransferCall_info_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusTransferCall_info_get(swigCPtr);
      return ret;
    } 
  }

  public OpalStatusTransferCall() : this(OPALPINVOKE.new_OpalStatusTransferCall(), true) {
  }

}
