/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OpalInstantMessage : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalInstantMessage(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OpalInstantMessage obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalInstantMessage() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalInstantMessage(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string from {
    set {
      OPALPINVOKE.OpalInstantMessage_from_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_from_get(swigCPtr);
      return ret;
    } 
  }

  public string to {
    set {
      OPALPINVOKE.OpalInstantMessage_to_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_to_get(swigCPtr);
      return ret;
    } 
  }

  public string host {
    set {
      OPALPINVOKE.OpalInstantMessage_host_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_host_get(swigCPtr);
      return ret;
    } 
  }

  public string conversationId {
    set {
      OPALPINVOKE.OpalInstantMessage_conversationId_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_conversationId_get(swigCPtr);
      return ret;
    } 
  }

  public string textBody {
    set {
      OPALPINVOKE.OpalInstantMessage_textBody_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_textBody_get(swigCPtr);
      return ret;
    } 
  }

  public uint bodyCount {
    set {
      OPALPINVOKE.OpalInstantMessage_bodyCount_set(swigCPtr, value);
    } 
    get {
      uint ret = OPALPINVOKE.OpalInstantMessage_bodyCount_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_char mimeType {
    set {
      OPALPINVOKE.OpalInstantMessage_mimeType_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OPALPINVOKE.OpalInstantMessage_mimeType_get(swigCPtr);
      SWIGTYPE_p_p_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_char bodies {
    set {
      OPALPINVOKE.OpalInstantMessage_bodies_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OPALPINVOKE.OpalInstantMessage_bodies_get(swigCPtr);
      SWIGTYPE_p_p_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
      return ret;
    } 
  }

  public uint messageId {
    set {
      OPALPINVOKE.OpalInstantMessage_messageId_set(swigCPtr, value);
    } 
    get {
      uint ret = OPALPINVOKE.OpalInstantMessage_messageId_get(swigCPtr);
      return ret;
    } 
  }

  public OpalInstantMessage() : this(OPALPINVOKE.new_OpalInstantMessage(), true) {
  }

}
