//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum OpalCallEndReason {
  OpalCallEndedByLocalUser,
  OpalCallEndedByNoAccept,
  OpalCallEndedByAnswerDenied,
  OpalCallEndedByRemoteUser,
  OpalCallEndedByRefusal,
  OpalCallEndedByNoAnswer,
  OpalCallEndedByCallerAbort,
  OpalCallEndedByTransportFail,
  OpalCallEndedByConnectFail,
  OpalCallEndedByGatekeeper,
  OpalCallEndedByNoUser,
  OpalCallEndedByNoBandwidth,
  OpalCallEndedByCapabilityExchange,
  OpalCallEndedByCallForwarded,
  OpalCallEndedBySecurityDenial,
  OpalCallEndedByLocalBusy,
  OpalCallEndedByLocalCongestion,
  OpalCallEndedByRemoteBusy,
  OpalCallEndedByRemoteCongestion,
  OpalCallEndedByUnreachable,
  OpalCallEndedByNoEndPoint,
  OpalCallEndedByHostOffline,
  OpalCallEndedByTemporaryFailure,
  OpalCallEndedByQ931Cause,
  OpalCallEndedByDurationLimit,
  OpalCallEndedByInvalidConferenceID,
  OpalCallEndedByNoDialTone,
  OpalCallEndedByNoRingBackTone,
  OpalCallEndedByOutOfService,
  OpalCallEndedByAcceptingCallWaiting,
  OpalCallEndedWithQ931Code = 0x100
}
