//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OpalMIME : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalMIME(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpalMIME obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalMIME() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalMIME(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string type {
    set {
      OPALPINVOKE.OpalMIME_type_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalMIME_type_get(swigCPtr);
      return ret;
    } 
  }

  public uint length {
    set {
      OPALPINVOKE.OpalMIME_length_set(swigCPtr, value);
    } 
    get {
      uint ret = OPALPINVOKE.OpalMIME_length_get(swigCPtr);
      return ret;
    } 
  }

  public string data {
    set {
      OPALPINVOKE.OpalMIME_data_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalMIME_data_get(swigCPtr);
      return ret;
    } 
  }

  public OpalMIME() : this(OPALPINVOKE.new_OpalMIME(), true) {
  }

}
