/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OpalParamCallCleared : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalParamCallCleared(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OpalParamCallCleared obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalParamCallCleared() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalParamCallCleared(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string callToken {
    set {
      OPALPINVOKE.OpalParamCallCleared_callToken_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalParamCallCleared_callToken_get(swigCPtr);
      return ret;
    } 
  }

  public OpalCallEndReason reason {
    set {
      OPALPINVOKE.OpalParamCallCleared_reason_set(swigCPtr, (int)value);
    } 
    get {
      OpalCallEndReason ret = (OpalCallEndReason)OPALPINVOKE.OpalParamCallCleared_reason_get(swigCPtr);
      return ret;
    } 
  }

  public OpalParamCallCleared() : this(OPALPINVOKE.new_OpalParamCallCleared(), true) {
  }

}
