/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OpalStatusMediaStream : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalStatusMediaStream(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OpalStatusMediaStream obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalStatusMediaStream() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalStatusMediaStream(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string callToken {
    set {
      OPALPINVOKE.OpalStatusMediaStream_callToken_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusMediaStream_callToken_get(swigCPtr);
      return ret;
    } 
  }

  public string identifier {
    set {
      OPALPINVOKE.OpalStatusMediaStream_identifier_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusMediaStream_identifier_get(swigCPtr);
      return ret;
    } 
  }

  public string type {
    set {
      OPALPINVOKE.OpalStatusMediaStream_type_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusMediaStream_type_get(swigCPtr);
      return ret;
    } 
  }

  public string format {
    set {
      OPALPINVOKE.OpalStatusMediaStream_format_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusMediaStream_format_get(swigCPtr);
      return ret;
    } 
  }

  public OpalMediaStates state {
    set {
      OPALPINVOKE.OpalStatusMediaStream_state_set(swigCPtr, (int)value);
    } 
    get {
      OpalMediaStates ret = (OpalMediaStates)OPALPINVOKE.OpalStatusMediaStream_state_get(swigCPtr);
      return ret;
    } 
  }

  public int volume {
    set {
      OPALPINVOKE.OpalStatusMediaStream_volume_set(swigCPtr, value);
    } 
    get {
      int ret = OPALPINVOKE.OpalStatusMediaStream_volume_get(swigCPtr);
      return ret;
    } 
  }

  public OpalStatusMediaStream() : this(OPALPINVOKE.new_OpalStatusMediaStream(), true) {
  }

}
