//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OpalStatusUserInput : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalStatusUserInput(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpalStatusUserInput obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalStatusUserInput() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalStatusUserInput(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string callToken {
    set {
      OPALPINVOKE.OpalStatusUserInput_callToken_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusUserInput_callToken_get(swigCPtr);
      return ret;
    } 
  }

  public string userInput {
    set {
      OPALPINVOKE.OpalStatusUserInput_userInput_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusUserInput_userInput_get(swigCPtr);
      return ret;
    } 
  }

  public uint duration {
    set {
      OPALPINVOKE.OpalStatusUserInput_duration_set(swigCPtr, value);
    } 
    get {
      uint ret = OPALPINVOKE.OpalStatusUserInput_duration_get(swigCPtr);
      return ret;
    } 
  }

  public OpalStatusUserInput() : this(OPALPINVOKE.new_OpalStatusUserInput(), true) {
  }

}
