/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum OpalLineAppearanceStates {
  OpalLineTerminated,
  OpalLineTrying,
  OpalLineProceeding,
  OpalLineRinging,
  OpalLineConnected,
  OpalLineSubcribed,
  OpalLineUnsubcribed,
  OpalLineIdle = OpalLineTerminated
}
