/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OpalParamSetUpCall : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalParamSetUpCall(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OpalParamSetUpCall obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalParamSetUpCall() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalParamSetUpCall(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string partyA {
    set {
      OPALPINVOKE.OpalParamSetUpCall_partyA_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalParamSetUpCall_partyA_get(swigCPtr);
      return ret;
    } 
  }

  public string partyB {
    set {
      OPALPINVOKE.OpalParamSetUpCall_partyB_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalParamSetUpCall_partyB_get(swigCPtr);
      return ret;
    } 
  }

  public string callToken {
    set {
      OPALPINVOKE.OpalParamSetUpCall_callToken_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalParamSetUpCall_callToken_get(swigCPtr);
      return ret;
    } 
  }

  public string alertingType {
    set {
      OPALPINVOKE.OpalParamSetUpCall_alertingType_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalParamSetUpCall_alertingType_get(swigCPtr);
      return ret;
    } 
  }

  public string protocolCallId {
    set {
      OPALPINVOKE.OpalParamSetUpCall_protocolCallId_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalParamSetUpCall_protocolCallId_get(swigCPtr);
      return ret;
    } 
  }

  public OpalParamProtocol overrides {
    set {
      OPALPINVOKE.OpalParamSetUpCall_overrides_set(swigCPtr, OpalParamProtocol.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OPALPINVOKE.OpalParamSetUpCall_overrides_get(swigCPtr);
      OpalParamProtocol ret = (cPtr == IntPtr.Zero) ? null : new OpalParamProtocol(cPtr, false);
      return ret;
    } 
  }

  public OpalParamSetUpCall() : this(OPALPINVOKE.new_OpalParamSetUpCall(), true) {
  }

}
