//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OpalInstantMessage : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalInstantMessage(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpalInstantMessage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalInstantMessage() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalInstantMessage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string from {
    set {
      OPALPINVOKE.OpalInstantMessage_from_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_from_get(swigCPtr);
      return ret;
    } 
  }

  public string to {
    set {
      OPALPINVOKE.OpalInstantMessage_to_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_to_get(swigCPtr);
      return ret;
    } 
  }

  public string host {
    set {
      OPALPINVOKE.OpalInstantMessage_host_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_host_get(swigCPtr);
      return ret;
    } 
  }

  public string conversationId {
    set {
      OPALPINVOKE.OpalInstantMessage_conversationId_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_conversationId_get(swigCPtr);
      return ret;
    } 
  }

  public string textBody {
    set {
      OPALPINVOKE.OpalInstantMessage_textBody_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_textBody_get(swigCPtr);
      return ret;
    } 
  }

  public uint bodyCount {
    set {
      OPALPINVOKE.OpalInstantMessage_bodyCount_set(swigCPtr, value);
    } 
    get {
      uint ret = OPALPINVOKE.OpalInstantMessage_bodyCount_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_char mimeType {
    set {
      OPALPINVOKE.OpalInstantMessage_mimeType_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = OPALPINVOKE.OpalInstantMessage_mimeType_get(swigCPtr);
      SWIGTYPE_p_p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_char bodies {
    set {
      OPALPINVOKE.OpalInstantMessage_bodies_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = OPALPINVOKE.OpalInstantMessage_bodies_get(swigCPtr);
      SWIGTYPE_p_p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
      return ret;
    } 
  }

  public uint messageId {
    set {
      OPALPINVOKE.OpalInstantMessage_messageId_set(swigCPtr, value);
    } 
    get {
      uint ret = OPALPINVOKE.OpalInstantMessage_messageId_get(swigCPtr);
      return ret;
    } 
  }

  public string htmlBody {
    set {
      OPALPINVOKE.OpalInstantMessage_htmlBody_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalInstantMessage_htmlBody_get(swigCPtr);
      return ret;
    } 
  }

  public OpalMIME bodyData {
    set {
      OPALPINVOKE.OpalInstantMessage_bodyData_set(swigCPtr, OpalMIME.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = OPALPINVOKE.OpalInstantMessage_bodyData_get(swigCPtr);
      OpalMIME ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalMIME(cPtr, false);
      return ret;
    } 
  }

  public OpalInstantMessage() : this(OPALPINVOKE.new_OpalInstantMessage(), true) {
  }

}
