/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OpalParamAnswerCall : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalParamAnswerCall(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OpalParamAnswerCall obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalParamAnswerCall() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalParamAnswerCall(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string callToken {
    set {
      OPALPINVOKE.OpalParamAnswerCall_callToken_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalParamAnswerCall_callToken_get(swigCPtr);
      return ret;
    } 
  }

  public OpalParamProtocol overrides {
    set {
      OPALPINVOKE.OpalParamAnswerCall_overrides_set(swigCPtr, OpalParamProtocol.getCPtr(value));
    } 
    get {
      IntPtr cPtr = OPALPINVOKE.OpalParamAnswerCall_overrides_get(swigCPtr);
      OpalParamProtocol ret = (cPtr == IntPtr.Zero) ? null : new OpalParamProtocol(cPtr, false);
      return ret;
    } 
  }

  public uint withMedia {
    set {
      OPALPINVOKE.OpalParamAnswerCall_withMedia_set(swigCPtr, value);
    } 
    get {
      uint ret = OPALPINVOKE.OpalParamAnswerCall_withMedia_get(swigCPtr);
      return ret;
    } 
  }

  public OpalParamAnswerCall() : this(OPALPINVOKE.new_OpalParamAnswerCall(), true) {
  }

}
