//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OpalMessagePtr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalMessagePtr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpalMessagePtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalMessagePtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalMessagePtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public OpalMessagePtr(OpalMessageType type) : this(OPALPINVOKE.new_OpalMessagePtr__SWIG_0((int)type), true) {
  }

  public OpalMessagePtr() : this(OPALPINVOKE.new_OpalMessagePtr__SWIG_1(), true) {
  }

  public OpalMessageType GetType() {
    OpalMessageType ret = (OpalMessageType)OPALPINVOKE.OpalMessagePtr_GetType(swigCPtr);
    return ret;
  }

  public OpalMessagePtr SetType(OpalMessageType type) {
    OpalMessagePtr ret = new OpalMessagePtr(OPALPINVOKE.OpalMessagePtr_SetType(swigCPtr, (int)type), false);
    return ret;
  }

  public string GetCallToken() {
    string ret = OPALPINVOKE.OpalMessagePtr_GetCallToken(swigCPtr);
    return ret;
  }

  public void SetCallToken(string token) {
    OPALPINVOKE.OpalMessagePtr_SetCallToken(swigCPtr, token);
  }

  public string GetCommandError() {
    string ret = OPALPINVOKE.OpalMessagePtr_GetCommandError(swigCPtr);
    return ret;
  }

  public OpalParamGeneral GetGeneralParams() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetGeneralParams(swigCPtr);
    OpalParamGeneral ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalParamGeneral(cPtr, false);
    return ret;
  }

  public OpalParamProtocol GetProtocolParams() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetProtocolParams(swigCPtr);
    OpalParamProtocol ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalParamProtocol(cPtr, false);
    return ret;
  }

  public OpalParamRegistration GetRegistrationParams() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetRegistrationParams(swigCPtr);
    OpalParamRegistration ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalParamRegistration(cPtr, false);
    return ret;
  }

  public OpalStatusRegistration GetRegistrationStatus() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetRegistrationStatus(swigCPtr);
    OpalStatusRegistration ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalStatusRegistration(cPtr, false);
    return ret;
  }

  public OpalParamSetUpCall GetCallSetUp() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetCallSetUp(swigCPtr);
    OpalParamSetUpCall ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalParamSetUpCall(cPtr, false);
    return ret;
  }

  public OpalStatusIncomingCall GetIncomingCall() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetIncomingCall(swigCPtr);
    OpalStatusIncomingCall ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalStatusIncomingCall(cPtr, false);
    return ret;
  }

  public OpalParamAnswerCall GetAnswerCall() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetAnswerCall(swigCPtr);
    OpalParamAnswerCall ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalParamAnswerCall(cPtr, false);
    return ret;
  }

  public OpalStatusUserInput GetUserInput() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetUserInput(swigCPtr);
    OpalStatusUserInput ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalStatusUserInput(cPtr, false);
    return ret;
  }

  public OpalStatusMessageWaiting GetMessageWaiting() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetMessageWaiting(swigCPtr);
    OpalStatusMessageWaiting ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalStatusMessageWaiting(cPtr, false);
    return ret;
  }

  public OpalStatusLineAppearance GetLineAppearance() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetLineAppearance(swigCPtr);
    OpalStatusLineAppearance ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalStatusLineAppearance(cPtr, false);
    return ret;
  }

  public OpalStatusCallCleared GetCallCleared() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetCallCleared(swigCPtr);
    OpalStatusCallCleared ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalStatusCallCleared(cPtr, false);
    return ret;
  }

  public OpalParamCallCleared GetClearCall() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetClearCall(swigCPtr);
    OpalParamCallCleared ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalParamCallCleared(cPtr, false);
    return ret;
  }

  public OpalStatusMediaStream GetMediaStream() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetMediaStream(swigCPtr);
    OpalStatusMediaStream ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalStatusMediaStream(cPtr, false);
    return ret;
  }

  public OpalParamSetUserData GetSetUserData() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetSetUserData(swigCPtr);
    OpalParamSetUserData ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalParamSetUserData(cPtr, false);
    return ret;
  }

  public OpalParamRecording GetRecording() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetRecording(swigCPtr);
    OpalParamRecording ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalParamRecording(cPtr, false);
    return ret;
  }

  public OpalStatusTransferCall GetTransferStatus() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetTransferStatus(swigCPtr);
    OpalStatusTransferCall ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalStatusTransferCall(cPtr, false);
    return ret;
  }

  public OpalPresenceStatus GetPresenceStatus() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetPresenceStatus(swigCPtr);
    OpalPresenceStatus ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalPresenceStatus(cPtr, false);
    return ret;
  }

  public OpalInstantMessage GetInstantMessage() {
    global::System.IntPtr cPtr = OPALPINVOKE.OpalMessagePtr_GetInstantMessage(swigCPtr);
    OpalInstantMessage ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalInstantMessage(cPtr, false);
    return ret;
  }

}
