//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OpalMessage : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalMessage(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpalMessage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalMessage() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalMessage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public OpalMessageType type {
    set {
      OPALPINVOKE.OpalMessage_type_set(swigCPtr, (int)value);
    } 
    get {
      OpalMessageType ret = (OpalMessageType)OPALPINVOKE.OpalMessage_type_get(swigCPtr);
      return ret;
    } 
  }

  public OpalMessageParam param {
    set {
      OPALPINVOKE.OpalMessage_param_set(swigCPtr, OpalMessageParam.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = OPALPINVOKE.OpalMessage_param_get(swigCPtr);
      OpalMessageParam ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalMessageParam(cPtr, false);
      return ret;
    } 
  }

  public OpalMessage() : this(OPALPINVOKE.new_OpalMessage(), true) {
  }

}
