//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OpalStatusRegistration : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpalStatusRegistration(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpalStatusRegistration obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpalStatusRegistration() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OPALPINVOKE.delete_OpalStatusRegistration(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string protocol {
    set {
      OPALPINVOKE.OpalStatusRegistration_protocol_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusRegistration_protocol_get(swigCPtr);
      return ret;
    } 
  }

  public string serverName {
    set {
      OPALPINVOKE.OpalStatusRegistration_serverName_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusRegistration_serverName_get(swigCPtr);
      return ret;
    } 
  }

  public string error {
    set {
      OPALPINVOKE.OpalStatusRegistration_error_set(swigCPtr, value);
    } 
    get {
      string ret = OPALPINVOKE.OpalStatusRegistration_error_get(swigCPtr);
      return ret;
    } 
  }

  public OpalRegistrationStates status {
    set {
      OPALPINVOKE.OpalStatusRegistration_status_set(swigCPtr, (int)value);
    } 
    get {
      OpalRegistrationStates ret = (OpalRegistrationStates)OPALPINVOKE.OpalStatusRegistration_status_get(swigCPtr);
      return ret;
    } 
  }

  public OpalProductDescription product {
    set {
      OPALPINVOKE.OpalStatusRegistration_product_set(swigCPtr, OpalProductDescription.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = OPALPINVOKE.OpalStatusRegistration_product_get(swigCPtr);
      OpalProductDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpalProductDescription(cPtr, false);
      return ret;
    } 
  }

  public OpalStatusRegistration() : this(OPALPINVOKE.new_OpalStatusRegistration(), true) {
  }

}
