/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalParamSetUpCall {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalParamSetUpCall(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalParamSetUpCall obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalParamSetUpCall(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPartyA(String value) {
    OPALJNI.OpalParamSetUpCall_partyA_set(swigCPtr, this, value);
  }

  public String getPartyA() {
    return OPALJNI.OpalParamSetUpCall_partyA_get(swigCPtr, this);
  }

  public void setPartyB(String value) {
    OPALJNI.OpalParamSetUpCall_partyB_set(swigCPtr, this, value);
  }

  public String getPartyB() {
    return OPALJNI.OpalParamSetUpCall_partyB_get(swigCPtr, this);
  }

  public void setCallToken(String value) {
    OPALJNI.OpalParamSetUpCall_callToken_set(swigCPtr, this, value);
  }

  public String getCallToken() {
    return OPALJNI.OpalParamSetUpCall_callToken_get(swigCPtr, this);
  }

  public void setAlertingType(String value) {
    OPALJNI.OpalParamSetUpCall_alertingType_set(swigCPtr, this, value);
  }

  public String getAlertingType() {
    return OPALJNI.OpalParamSetUpCall_alertingType_get(swigCPtr, this);
  }

  public void setProtocolCallId(String value) {
    OPALJNI.OpalParamSetUpCall_protocolCallId_set(swigCPtr, this, value);
  }

  public String getProtocolCallId() {
    return OPALJNI.OpalParamSetUpCall_protocolCallId_get(swigCPtr, this);
  }

  public void setOverrides(OpalParamProtocol value) {
    OPALJNI.OpalParamSetUpCall_overrides_set(swigCPtr, this, OpalParamProtocol.getCPtr(value), value);
  }

  public OpalParamProtocol getOverrides() {
    long cPtr = OPALJNI.OpalParamSetUpCall_overrides_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OpalParamProtocol(cPtr, false);
  }

  public void setExtraCount(long value) {
    OPALJNI.OpalParamSetUpCall_extraCount_set(swigCPtr, this, value);
  }

  public long getExtraCount() {
    return OPALJNI.OpalParamSetUpCall_extraCount_get(swigCPtr, this);
  }

  public void setExtras(OpalMIME value) {
    OPALJNI.OpalParamSetUpCall_extras_set(swigCPtr, this, OpalMIME.getCPtr(value), value);
  }

  public OpalMIME getExtras() {
    long cPtr = OPALJNI.OpalParamSetUpCall_extras_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OpalMIME(cPtr, false);
  }

  public OpalParamSetUpCall() {
    this(OPALJNI.new_OpalParamSetUpCall(), true);
  }

}
