/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalMIME {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalMIME(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalMIME obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalMIME(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(String value) {
    OPALJNI.OpalMIME_type_set(swigCPtr, this, value);
  }

  public String getType() {
    return OPALJNI.OpalMIME_type_get(swigCPtr, this);
  }

  public void setLength(long value) {
    OPALJNI.OpalMIME_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return OPALJNI.OpalMIME_length_get(swigCPtr, this);
  }

  public void setData(String value) {
    OPALJNI.OpalMIME_data_set(swigCPtr, this, value);
  }

  public String getData() {
    return OPALJNI.OpalMIME_data_get(swigCPtr, this);
  }

  public OpalMIME() {
    this(OPALJNI.new_OpalMIME(), true);
  }

}
