/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalPresenceStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OpalPresenceStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalPresenceStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalPresenceStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_entity(String value) {
    OPALJNI.OpalPresenceStatus_m_entity_set(swigCPtr, this, value);
  }

  public String getM_entity() {
    return OPALJNI.OpalPresenceStatus_m_entity_get(swigCPtr, this);
  }

  public void setM_target(String value) {
    OPALJNI.OpalPresenceStatus_m_target_set(swigCPtr, this, value);
  }

  public String getM_target() {
    return OPALJNI.OpalPresenceStatus_m_target_get(swigCPtr, this);
  }

  public void setM_service(String value) {
    OPALJNI.OpalPresenceStatus_m_service_set(swigCPtr, this, value);
  }

  public String getM_service() {
    return OPALJNI.OpalPresenceStatus_m_service_get(swigCPtr, this);
  }

  public void setM_contact(String value) {
    OPALJNI.OpalPresenceStatus_m_contact_set(swigCPtr, this, value);
  }

  public String getM_contact() {
    return OPALJNI.OpalPresenceStatus_m_contact_get(swigCPtr, this);
  }

  public void setM_capabilities(String value) {
    OPALJNI.OpalPresenceStatus_m_capabilities_set(swigCPtr, this, value);
  }

  public String getM_capabilities() {
    return OPALJNI.OpalPresenceStatus_m_capabilities_get(swigCPtr, this);
  }

  public void setM_state(OpalPresenceStates value) {
    OPALJNI.OpalPresenceStatus_m_state_set(swigCPtr, this, value.swigValue());
  }

  public OpalPresenceStates getM_state() {
    return OpalPresenceStates.swigToEnum(OPALJNI.OpalPresenceStatus_m_state_get(swigCPtr, this));
  }

  public void setM_activities(String value) {
    OPALJNI.OpalPresenceStatus_m_activities_set(swigCPtr, this, value);
  }

  public String getM_activities() {
    return OPALJNI.OpalPresenceStatus_m_activities_get(swigCPtr, this);
  }

  public void setM_note(String value) {
    OPALJNI.OpalPresenceStatus_m_note_set(swigCPtr, this, value);
  }

  public String getM_note() {
    return OPALJNI.OpalPresenceStatus_m_note_get(swigCPtr, this);
  }

  public void setM_infoType(String value) {
    OPALJNI.OpalPresenceStatus_m_infoType_set(swigCPtr, this, value);
  }

  public String getM_infoType() {
    return OPALJNI.OpalPresenceStatus_m_infoType_get(swigCPtr, this);
  }

  public void setM_infoData(String value) {
    OPALJNI.OpalPresenceStatus_m_infoData_set(swigCPtr, this, value);
  }

  public String getM_infoData() {
    return OPALJNI.OpalPresenceStatus_m_infoData_get(swigCPtr, this);
  }

  public OpalPresenceStatus() {
    this(OPALJNI.new_OpalPresenceStatus(), true);
  }

}
