/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalStatusIVR {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalStatusIVR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalStatusIVR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalStatusIVR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallToken(String value) {
    OPALJNI.OpalStatusIVR_callToken_set(swigCPtr, this, value);
  }

  public String getCallToken() {
    return OPALJNI.OpalStatusIVR_callToken_get(swigCPtr, this);
  }

  public void setVariables(String value) {
    OPALJNI.OpalStatusIVR_variables_set(swigCPtr, this, value);
  }

  public String getVariables() {
    return OPALJNI.OpalStatusIVR_variables_get(swigCPtr, this);
  }

  public OpalStatusIVR() {
    this(OPALJNI.new_OpalStatusIVR(), true);
  }

}
