/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalParamCallCleared {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalParamCallCleared(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalParamCallCleared obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalParamCallCleared(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallToken(String value) {
    OPALJNI.OpalParamCallCleared_callToken_set(swigCPtr, this, value);
  }

  public String getCallToken() {
    return OPALJNI.OpalParamCallCleared_callToken_get(swigCPtr, this);
  }

  public void setReason(OpalCallEndReason value) {
    OPALJNI.OpalParamCallCleared_reason_set(swigCPtr, this, value.swigValue());
  }

  public OpalCallEndReason getReason() {
    return OpalCallEndReason.swigToEnum(OPALJNI.OpalParamCallCleared_reason_get(swigCPtr, this));
  }

  public OpalParamCallCleared() {
    this(OPALJNI.new_OpalParamCallCleared(), true);
  }

}
