/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalStatusMediaStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalStatusMediaStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalStatusMediaStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalStatusMediaStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallToken(String value) {
    OPALJNI.OpalStatusMediaStream_callToken_set(swigCPtr, this, value);
  }

  public String getCallToken() {
    return OPALJNI.OpalStatusMediaStream_callToken_get(swigCPtr, this);
  }

  public void setIdentifier(String value) {
    OPALJNI.OpalStatusMediaStream_identifier_set(swigCPtr, this, value);
  }

  public String getIdentifier() {
    return OPALJNI.OpalStatusMediaStream_identifier_get(swigCPtr, this);
  }

  public void setType(String value) {
    OPALJNI.OpalStatusMediaStream_type_set(swigCPtr, this, value);
  }

  public String getType() {
    return OPALJNI.OpalStatusMediaStream_type_get(swigCPtr, this);
  }

  public void setFormat(String value) {
    OPALJNI.OpalStatusMediaStream_format_set(swigCPtr, this, value);
  }

  public String getFormat() {
    return OPALJNI.OpalStatusMediaStream_format_get(swigCPtr, this);
  }

  public void setState(OpalMediaStates value) {
    OPALJNI.OpalStatusMediaStream_state_set(swigCPtr, this, value.swigValue());
  }

  public OpalMediaStates getState() {
    return OpalMediaStates.swigToEnum(OPALJNI.OpalStatusMediaStream_state_get(swigCPtr, this));
  }

  public void setVolume(int value) {
    OPALJNI.OpalStatusMediaStream_volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return OPALJNI.OpalStatusMediaStream_volume_get(swigCPtr, this);
  }

  public void setWatermark(String value) {
    OPALJNI.OpalStatusMediaStream_watermark_set(swigCPtr, this, value);
  }

  public String getWatermark() {
    return OPALJNI.OpalStatusMediaStream_watermark_get(swigCPtr, this);
  }

  public OpalStatusMediaStream() {
    this(OPALJNI.new_OpalStatusMediaStream(), true);
  }

}
