/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package -I/home/robertj/opal/include;

public final class OpalSilenceDetectModes {
  public final static OpalSilenceDetectModes OpalSilenceDetectNoChange = new OpalSilenceDetectModes("OpalSilenceDetectNoChange");
  public final static OpalSilenceDetectModes OpalSilenceDetectDisabled = new OpalSilenceDetectModes("OpalSilenceDetectDisabled");
  public final static OpalSilenceDetectModes OpalSilenceDetectFixed = new OpalSilenceDetectModes("OpalSilenceDetectFixed");
  public final static OpalSilenceDetectModes OpalSilenceDetectAdaptive = new OpalSilenceDetectModes("OpalSilenceDetectAdaptive");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OpalSilenceDetectModes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OpalSilenceDetectModes.class + " with value " + swigValue);
  }

  private OpalSilenceDetectModes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OpalSilenceDetectModes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OpalSilenceDetectModes(String swigName, OpalSilenceDetectModes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OpalSilenceDetectModes[] swigValues = { OpalSilenceDetectNoChange, OpalSilenceDetectDisabled, OpalSilenceDetectFixed, OpalSilenceDetectAdaptive };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

