/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip;

public class OpalParamRegistration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OpalParamRegistration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalParamRegistration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      exampleJNI.delete_OpalParamRegistration(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setM_protocol(String value) {
    exampleJNI.OpalParamRegistration_m_protocol_set(swigCPtr, this, value);
  }

  public String getM_protocol() {
    return exampleJNI.OpalParamRegistration_m_protocol_get(swigCPtr, this);
  }

  public void setM_identifier(String value) {
    exampleJNI.OpalParamRegistration_m_identifier_set(swigCPtr, this, value);
  }

  public String getM_identifier() {
    return exampleJNI.OpalParamRegistration_m_identifier_get(swigCPtr, this);
  }

  public void setM_hostName(String value) {
    exampleJNI.OpalParamRegistration_m_hostName_set(swigCPtr, this, value);
  }

  public String getM_hostName() {
    return exampleJNI.OpalParamRegistration_m_hostName_get(swigCPtr, this);
  }

  public void setM_authUserName(String value) {
    exampleJNI.OpalParamRegistration_m_authUserName_set(swigCPtr, this, value);
  }

  public String getM_authUserName() {
    return exampleJNI.OpalParamRegistration_m_authUserName_get(swigCPtr, this);
  }

  public void setM_password(String value) {
    exampleJNI.OpalParamRegistration_m_password_set(swigCPtr, this, value);
  }

  public String getM_password() {
    return exampleJNI.OpalParamRegistration_m_password_get(swigCPtr, this);
  }

  public void setM_adminEntity(String value) {
    exampleJNI.OpalParamRegistration_m_adminEntity_set(swigCPtr, this, value);
  }

  public String getM_adminEntity() {
    return exampleJNI.OpalParamRegistration_m_adminEntity_get(swigCPtr, this);
  }

  public void setM_timeToLive(long value) {
    exampleJNI.OpalParamRegistration_m_timeToLive_set(swigCPtr, this, value);
  }

  public long getM_timeToLive() {
    return exampleJNI.OpalParamRegistration_m_timeToLive_get(swigCPtr, this);
  }

  public void setM_restoreTime(long value) {
    exampleJNI.OpalParamRegistration_m_restoreTime_set(swigCPtr, this, value);
  }

  public long getM_restoreTime() {
    return exampleJNI.OpalParamRegistration_m_restoreTime_get(swigCPtr, this);
  }

  public void setM_eventPackage(String value) {
    exampleJNI.OpalParamRegistration_m_eventPackage_set(swigCPtr, this, value);
  }

  public String getM_eventPackage() {
    return exampleJNI.OpalParamRegistration_m_eventPackage_get(swigCPtr, this);
  }

  public OpalParamRegistration() {
    this(exampleJNI.new_OpalParamRegistration(), true);
  }

}
