#
# Makefile
#
# Makefile for h224test
#
# Copyright (c) 2008 Post Increment
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is Open Phone Abstraction Library.
#
# The Initial Developer of the Original Code is Equivalence Pty. Ltd.
#
# Contributor(s): ______________________________________.
#
# $Revision: 21713 $
# $Auther$
# $Date: 2008-12-08 19:14:44 +1100 (Mon, 08 Dec 2008) $
#

PROG = h224test
SOURCES := main.cxx

ifdef OPALDIR
  include $(OPALDIR)/opal_inc.mak
else
  include $(shell pkg-config opal --variable=makedir)/opal_inc.mak
endif

# End of Makefile
